[package]
name = "lib_count"
version = "0.1.0"
authors = ["Brian <brianmr31@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "count"
crate-type = ["staticlib", "cdylib"]

[dependencies]
postgres= "*"
